const SESSION_STORAGE_LOAD = process.env.SESSION_STORAGE_LOAD;
const LOAD_BUTTON_ID = process.env.LOAD_BUTTON_ID;
const APP_PLACEHOLDER_ID = process.env.APP_PLACEHOLDER_ID;
const REMOTE_APP_URL = process.env.REMOTE_APP_URL;
const SESSION_STORAGE_GEOLOCATION = process.env.SESSION_STORAGE_GEOLOCATION;

module.exports = {SESSION_STORAGE_LOAD, SESSION_STORAGE_GEOLOCATION, LOAD_BUTTON_ID, APP_PLACEHOLDER_ID, REMOTE_APP_URL};
